#ifndef CONFIG
#define CONFIG

#define DATA_MESSAGE_SIZE 20
#define DIS_BROADCAST_SPEED 2000
#define NODE_DISCARD_THRESHOLD (10 * DIS_BROADCAST_SPEED)
#define DATA_TTL 6
#define ACK_TTL 6
#define PEER_CHANNEL 11
#define PEER_ENCRYPT false
#define RETRY_TIME_THRESHOLD 2
#define RETRY_CNT_THRESHOLD 3
#define RETRY_JOURNAL_SIZE 10
#define NODE_REGISTRY_SIZE 10
#define TESTING_ENABLED false
#define SERIAL_MESSAGE_SENDING_ENABLED false
#define BLE_ENABLED false

#endif // !CONFIG
